version: "3.9"

services:
  db:
    image: postgres:18
    container_name: erdtree-cards-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: cards
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  web:
    build: .
    container_name: erdtree-cards-web
    ports:
      - "3000:3000"
      - "9229:9229"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/cards
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data:
